spring:
  application:
    name: mscloudgateway
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscardrealm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://mscredito-eureka-user:mspass8821@${EUREKA_SERVER}:8761/eureka